services:
  frontend:
    image: "docker-compose-frontend"
    build: ./frontend
    ports: 
      - "3000:3000"
      - "80:3000"
    restart: on-failure
    depends_on:
      - backend
  backend:
    image: "docker-compose-backend"
    build: ./backend
    ports:
      - "8000:8000"
    restart: on-failure 